### ISSUE TITLE
Adding tab to F1 with client settings

### ISSUE THREAD

**Issue by Flapchik** [wgetJane/ttt-combattext#1]
Hey.
I want to suggest a new tab in the F1 help menu. In this tab, you can customize the color, font, font size, etc.

Example
![image](https://user-images.githubusercontent.com/58729268/104605825-09862e00-5690-11eb-9702-6c9a9fc44f99.png)

**Comment by wgetJane** [comment]
![a](https://user-images.githubusercontent.com/52103358/104728539-fba8d980-5771-11eb-99a9-7f6a18c943af.png)
![b](https://user-images.githubusercontent.com/52103358/104728561-08c5c880-5772-11eb-9381-85ce170fd8d1.png)
